version: '3'
services:
  app:
    image: app-tms-image:v2
    ports:
      - '8080:8080'
    depends_on:
      - database
      - kafka
    environment:
      - DB_CONNECTION_URL=tms_db_mysql_hostname
      - DB_PORT=3306
      - DB_NAME=tmsdb
    networks:
      - tms_network

  database:
    hostname: tms_db_mysql_hostname
    image: mysql:8.0.36-debian
    restart: always
    environment:
      MYSQL_USER : aytan
      MYSQL_PASSWORD : 12345 #Aytan_Jafar%03
      MYSQL_DATABASE : tmsdb
      MYSQL_ROOT_PASSWORD : 12345
    ports:
      - '3307:3306'
    volumes:
      - ./var/lib:/var/lib/mysql
    networks:
      - tms_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '59092:59092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:59092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - tms_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_JVMFLAGS: "-Djute.maxbuffer=4194304"
    ports:
      - '52181:2181'
#    networks:
#      - tms_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9091:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - tms_network

networks:
  tms_network:
    driver: bridge
